name: CI

on:
  push:
    branches:
      - main
      - jcortejoso/*
  pull_request:

jobs:
  build:
    strategy:
      matrix:
        node:
          - 20.x
        os:
          - ubuntu-latest

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - uses: actions/cache@v4
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ matrix.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ matrix.os }}-yarn-

      - name: Install dependencies
        run: yarn install

      - name: Run GraphQL codegen
        run: yarn codegen

      - name: Build project
        run: yarn build

      - name: Get Graph Auth Token from Akeyless
        uses:
          docker://us-west1-docker.pkg.dev/devopsre/akeyless-public/akeyless-action:latest
        with:
          api-url: https://api.gateway.akeyless.celo-networks-dev.org
          access-id: p-kf9vjzruht6l
          static-secrets: '{"/static-secrets/partner-engineering-circle/thegraph-apikey":"GRAPH_API_KEY"}'

      - name: Authenticate with theGraph hosted service
        run: yarn graph auth --product hosted-service $GRAPH_API_KEY

      - name: Deploy to Graph Hosted service
        if: false
        run: yarn deploy-celo
